

networks:
  shared-net:
    external: true
    driver: overlay
  
  service:
    driver: bridge

# volumes:

services:
  nginx:
    image: nginx:alpine
    ports: 
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - service
    depends_on:
      - api
  
  api:
    build:
      context: .
      dockerfile: ./docker/service/Dockerfile
    networks:
      - service
    environment:
      - REPLICA_COUNT=2
    entrypoint: ["sh", "./docker/api/entrypoint.sh"]
