[project]
name = "fastapi-best-practices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.116.1",
    "ruff>=0.12.4",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
